### ISSUE TITLE
Caddy example with existing reverse proxy handlers?

### ISSUE THREAD

**Issue by carterbryden** [darkweak/souin#141]
Are there any examples of how the Caddy plugin could work with existing reverse proxy handlers?

I'm getting errors like this when I try to slot this in as one of my handlers, similar to what you're doing in this example:
https://github.com/darkweak/souin/blob/master/plugins/caddy/examples/configuration-not-distributed.json

Error (sorry it's not formatted as code, it has no new lines then):

{"level":"debug","ts":1634541669.0222538,"logger":"http.stdlib","msg":"http2: panic serving 140.99.93.52:34856: runtime error: invalid memory address or nil pointer dereference\ngoroutine 414 [running]:\nnet/http.(*http2serverConn).runHandler.func1()\n\tnet/http/h2_bundle.go:5825 +0x125\npanic({0x1787780, 0x29d45b0})\n\truntime/panic.go:1038 +0x215\nio.ReadAll({0x0, 0x0})\n\tio/io.go:633 +0xd4\nio/ioutil.ReadAll(...)\n\tio/ioutil/ioutil.go:27\ngithub.com/darkweak/souin/plugins.(*CustomWriter).Send(0xc0004ba0a0)\n\tgithub.com/darkweak/souin@v1.5.10/plugins/base.go:55 +0x4a\ngithub.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP.func1({0xc0198e5b00, 0xc01b974ac0}, 0xc000216ee0)\n\tgithub.com/darkweak/souin/plugins/caddy@v0.0.0-20211001161855-2103f3697786/httpcache.go:97 +0x10f\ngithub.com/darkweak/souin/plugins.DefaultSouinPluginCallback({0x1cd0d50, 0xc0004ba0a0}, 0xc01b255d00, {0x1cfe8a8, 0xc01b23a000}, {0x0, 0x0}, 0xc01b974a80)\n\tgithub.com/darkweak/souin@v1.5.10/plugins/base.go:147 +0x49c\ngithub.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP(0xc01c9388f0, {0x7f19d0c8be38, 0xc02d4c81e0}, 0xc01b255c00, {0x1cbdde0, 0xc0004ba060})\n\tgithub.com/darkweak/souin/plugins/caddy@v0.0.0-20211001161855-2103f3697786/httpcache.go:86 +0x71d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc019b6e5e0, {0x1cd2610, 0xc00000f4b0}, 0xc01b255c00, {0x1cbdde0, 0xc0004ba060})\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/metrics.go:133 +0x51f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x1cd2610, 0xc00000f4b0}, 0x1cbdde0)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:263 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1cbdde0, {0x1cd2610, 0xc00000f4b0}, 0xc01c900288)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1cd2610, 0xc00000f4b0}, 0xc01b255c00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:235 +0x292\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc01c9002d0, {0x1cd2610, 0xc00000f4b0}, 0xc01c900210)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1cd2610, 0xc00000f4b0}, 0xc01b255c00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:203 +0x227\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc01c900258, {0x1cd2610, 0xc00000f4b0}, 0xc01c900150)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1cd2610, 0xc00000f4b0}, 0xc01b255c00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:203 +0x227\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc01c9001e0, {0x1cd2610, 0xc00000f4b0}, 0xc01c900090)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1cd2610, 0xc00000f4b0}, 0xc01b255c00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:203 +0x227\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc01c900120, {0x1cd2610, 0xc00000f4b0}, 0x2)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1cd2610, 0xc00000f4b0}, 0xc01b255c00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/routes.go:203 +0x227\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x74aaa6, {0x1cd2610, 0xc00000f4b0}, 0x19a0729)\n\tgithub.com/caddyserver/caddy/v2@v2.4.5/modules/caddyhttp/caddyhttp.go:57 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc02d4c8120, {0x1cd2610, 0xc00000f4b0}, 0x0, {0x1cbdde0, 0xc019b6e700})\n\tgithub.com/caddys
The error gets cut short there.

**Comment by darkweak** [comment]
Everything should be okay now.
