### ISSUE TITLE
Souin errors with some traefik services

### ISSUE THREAD

**Issue by choelzl** [darkweak/souin#167]
I struggle to get souin to work as a traefik plugin in order to cache resized images and other files/documents from a CDN.

Traefik Version: `2.5.6`
Souin Version: `1.5.11-beta6` (as traefik plugin)

Using Service Rules:
```
    - "traefik.http.middlewares.cdn-cache.plugin.souin.api.souin.enable=true"
    - "traefik.http.middlewares.cdn-cache.plugin.souin.default_cache.headers=Authorization,Content-Type"
    - "traefik.http.middlewares.cdn-cache.plugin.souin.default_cache.ttl=600s"
```

With `whoami` service works: `cache-status Souin; hit; ttl=25`
With `imgproxy`, encounters errors: `cache-status Souin; fwd=uri-miss; stored` (keeps missing/storing)

Traefik Logs:

> 
> level=error msg="plugins-storage/sources/gop-1760229924/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/rfc/standalone.go:335:11: panic" plugin=plugin-souin module=github.com/darkweak/souin
> level=error msg="plugins-storage/sources/gop-1760229924/src/github.com/darkweak/souin/plugins/traefik/base.go:60:20: panic" module=github.com/darkweak/souin plugin=plugin-souin
> level=error msg="plugins-storage/sources/gop-1760229924/src/github.com/darkweak/souin/plugins/traefik/main.go:203:7: panic" plugin=plugin-souin module=github.com/darkweak/souin
> level=error msg="plugins-storage/sources/gop-1760229924/src/github.com/darkweak/souin/plugins/traefik/base.go:110:14: panic" plugin=plugin-souin module=github.com/darkweak/souin
> level=error msg="plugins-storage/sources/gop-1760229924/src/github.com/darkweak/souin/plugins/traefik/main.go:162:22: panic" module=github.com/darkweak/souin plugin=plugin-souin
> level=error msg="Recovered from panic in HTTP handler [[...]:45034 - /p:sharp/rs:fill:320::/g:sm/czM6Ly9waG90b3MvQUkvaW5kZXguanBn]: reflect: Method on nil interface value" middlewareName=traefik-internal-recovery middlewareType=Recovery
> level=error msg="Stack: goroutine 18743 [running]:\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x7ff609d2c178, 0xc000c743b0}, 0xc00455e100)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:46 +0x225\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0x3ab91a0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\nreflect.Value.Method({0x2fc4d00, 0xc005fb1f00, 0x1}, 0x1)\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:1669 +0x13e\ngithub.com/traefik/yaegi/interp.getIndexBinMethod.func1(0x4684d9)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1676 +0xaf\ngithub.com/traefik/yaegi/interp.runCfg(0xc003e19560, 0xc0052db810, 0x3, 0x2cd25a0)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc004378e58, 0x1, 0x4})\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1023 +0x4a5\ngithub.com/traefik/yaegi/stdlib._io_ReadCloser.Read(...)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/stdlib/go1_17_io.go:152\nio.ReadAll({0x7ff609a95b78, 0xc00282d0e0})\n\t/usr/local/golang/1.10.8/go/src/io/io.go:633 +0xfe\nio/ioutil.ReadAll({0x7ff609a95b78, 0xc00282d0e0})\n\t/usr/local/golang/1.10.8/go/src/io/ioutil/ioutil.go:27 +0x25\nreflect.Value.call({0x2e58fe0, 0x36d6848, 0x3040640}, {0x355d780, 0x4}, {0xc004378e40, 0x1, 0x7ff609caa8f0})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:543 +0x814\nreflect.Value.Call({0x2e58fe0, 0x36d6848, 0x4517f2}, {0xc004378e40, 0x1, 0x1})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:339 +0xc5\ngithub.com/traefik/yaegi/interp.callBin.func1({0x2e58fe0, 0x36d6848, 0x198}, {0xc004378e40, 0xc0040294a0, 0xc0040b97a0})\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1472 +0x28\ngithub.com/traefik/yaegi/interp.callBin.func8(0xc0052db760)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1613 +0x158\ngithub.com/traefik/yaegi/interp.runCfg(0xc00035e6c0, 0xc0052db760, 0x0, 0xc003fe0800)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc000cb0b00)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1422 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc004037320, 0xc000cb0b00, 0xc0047b0508, 0x3453a60)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc000f52d10)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1422 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc0005626c0, 0xc000f52d10, 0xc0047b0768, 0x33620e0)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc000ffae70)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1422 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc00401e240, 0xc000ffae70, 0x39, 0x3453a60)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc0015fbf50, 0x2, 0x4})\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1023 +0x4a5\ngithub.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/stdlib/go1_17_net_http.go:288\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc00148a400, {0x7ff609d2c178, 0xc000c743b0}, 0x3489840)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:38 +0xf6\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00148e180, {0x7ff609d2c178, 0xc000c743b0}, 0xc00455e100)\n\t/home/semaphore/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x270\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x40fbd4, {0x7ff609d2c178, 0xc000c743b0}, 0xc004157270)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddOriginFields({0x7ff609d2c1c8, 0xc000c743a8}, 0x357d4a1, {0x3afe100, 0xc001df7750}, 0xc005837600)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:55 +0x1a2\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000cbdb80, {0x7ff609d2c1c8, 0xc000c743a8}, 0x3ab5901)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc004029e30, {0x7ff609d2c1c8, 0xc000c743a8}, 0xc00455e000, 0xc004157448)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x57b\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x7ff609d2c1c8, 0xc000c743a8}, 0xc000c743a8)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x68\nnet/http.HandlerFunc.ServeHTTP(0xc0058539e0, {0x7ff609d2c1c8, 0xc000c743a8}, 0xc0014845e0)\n\t/usr/local/golang/1.10.8/go/src/net/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc004a8aee0, {0x7ff609d2c178, 0xc000c743a0}, 0xc00455e000)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/metrics/metrics.go:121 +0x722\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0xc004101560, {0x3b3df80, 0xc001ebc1e0}, 0xc003f60700, {0x3afe080, 0xc004a8aee0})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:227 +0xfa3\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.WrapHandler.func1.1({0x3b3df80, 0xc001ebc1e0}, 0xc0015f0840)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:71 +0x3b\nnet/http.HandlerFunc.ServeHTTP(0xc0030d10e0, {0x3b3df80, 0xc001ebc1e0}, 0x4ee11e)\n\t/usr/local/golang/1.10.8/go/src/net/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/server/router/tcp.(*Manager).buildEntryPointHandler.func1({0x3b3df80, 0xc001ebc1e0}, 0xc003f60700)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/tcp/router.go:194 +0x199\nnet/http.HandlerFunc.ServeHTTP(0x0, {0x3b3df80, 0xc001ebc1e0}, 0xc0007626d0)\n\t/usr/local/golang/1.10.8/go/src/net/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0xc000129450, {0x3b3df80, 0xc001ebc1e0}, 0x9)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/handler_switcher.go:23 +0x62\ngithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000129450, {0x3b3df80, 0xc001ebc1e0}, 0xc003f60700)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:189 +0xca\nnet/http.serverHandler.ServeHTTP({0x0}, {0x3b3df80, 0xc001ebc1e0}, 0xc003f60700)\n\t/usr/local/golang/1.10.8/go/src/net/http/server.go:2879 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0x3b64980, 0xc001626d20}, 0xc004d63c00, {0xc00033a620}}, {0x3b3df80, 0xc001ebc1e0}, 0xc003f60700)\n\t/usr/local/golang/1.10.8/go/src/net/http/server.go:3480 +0x245\nnet/http.(*http2serverConn).runHandler(0x100000003b2ed60, 0xc91200, 0x36d4000, 0xc004df6fb8)\n\t/usr/local/golang/1.10.8/go/src/net/http/h2_bundle.go:5849 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\t/usr/local/golang/1.10.8/go/src/net/http/h2_bundle.go:5579 +0x510\n" middlewareType=Recovery middlewareName=traefik-internal-recovery

I dont know if it is helpful but those are some headers returned by an image from `imgproxy`:
> content-type: image/jpg
> content-disposition: inline, filename="index.jpg"
> cache-control: max-age=600, public
> expires: * * * (date in the future)
> vary: Accept

Potentially Similar:
#97

**Comment by darkweak** [comment]
I @choelzl thank you for your report, I'm on it 👌
