### ISSUE TITLE
Surrogate keys still not flushing correctly

### ISSUE THREAD

**Issue by mattvb91** [darkweak/souin#223]
I've made some slight changes to the code try help debug this issue that I will document below. It would also be nice to have these logs showing if the log is set to `DEBUG` mode to further increase visibility. 

Am I right in assuming I should be using the `*zap.logger` instance that gets passed into the config instead of `fmt.Println` and just call `logger.debug('my messages')`? I can open a PR if thats something that could be added.

```go
//cache/surrogate/providers/common.go
func (s *baseStorage) storeTag(tag string, cacheKey string, re *regexp.Regexp) {
	if currentValue, b := s.Storage[tag]; s.dynamic || b {
		if !re.MatchString(currentValue) {
			fmt.Println("Storing:", tag, cacheKey) // <-- ADDED
			s.Storage[tag] = currentValue + souinStorageSeparator + cacheKey
		}
	}
}
```

```go
//cache/surrogate/providers/common.go
func (s *baseStorage) purgeTag(tag string) []string {
	fmt.Println("Purging:", tag) // <-- ADDED

	toInvalidate := s.Storage[tag]
	delete(s.Storage, tag)
	if !s.keepStale {
		toInvalidate = toInvalidate + "," + s.Storage[stalePrefix+tag]
		delete(s.Storage, stalePrefix+tag)
	}
	return strings.Split(toInvalidate, souinStorageSeparator)
}
```

I have an API request that gets the following surrogate keys set on it:

```
//GET blaaa-4hwurl6y.localhost/api/shop/get/
"blaaa-4hwurl6y.localhost, product-0075c4fc-1c23-4ee7-bb94-76d97802ff03, category-77c72bf5-4f2e-4831-af7c-acfef65b8781"
```

The frontend will request data from the API and then render itself and the resulting output in the caddy log is this:

```
Storing: blaaa-4hwurl6y.localhost GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F
Storing: product-0075c4fc-1c23-4ee7-bb94-76d97802ff03 GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F
Storing: category-77c72bf5-4f2e-4831-af7c-acfef65b8781 GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F
Storing: blaaa-4hwurl6y.localhost GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br
Storing: product-0075c4fc-1c23-4ee7-bb94-76d97802ff03 GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br
Storing: category-77c72bf5-4f2e-4831-af7c-acfef65b8781 GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br
```

So far so good, each individual category, product and root page got added.

I can also see:

```json
/__cache/souin

[
"GET-blaaa-4hwurl6y.localhost-/api/shop/get/",
"GET-blaaa-4hwurl6y.localhost-/{-VARY-}Accept-Encoding:gzip, deflate, br"
]
```

```json
/__cache/souin/surrogate_keys
{
"blaaa-4hwurl6y.localhost": ",GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F,GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br",
"category-77c72bf5-4f2e-4831-af7c-acfef65b8781": ",GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F,GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br",
"product-0075c4fc-1c23-4ee7-bb94-76d97802ff03": ",GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F,GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3Agzip%2C+deflate%2C+br"
}
```

So again, the frontend triggers the backend API so I am expecting multiple cache entries for the keys. Both `/__cache/souin` and `/__cache/souin/surrogate_keys` look good right now

I now make some changes in the backend which trigger a flush on the `blaaa-4hwurl6y.localhost` surrogate key. (I use the domain name as a global tag if I need to flush all pages associated with that domain (for example top level site name change or something)).

Caddy log:
```
Purging: blaaa-4hwurl6y.localhost
```

This works fine and I can see that at `/__cache/souin` everything gets cleaned up. 

Now if I come along and do a 

```
curl --location --request GET 'http://blaaa-4hwurl6y.localhost/'
```

Caddy log:
```
Storing: blaaa-4hwurl6y.localhost GET-blaaa-4hwurl6y.localhost-%2F%7B-VARY-%7DAccept-Encoding%3A
```

At this point it gets difficult to trace but essentially what happens is the global surrogate key no longer has `GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2F` in it:

```json
/__cache/souin/surrogate_keys
"blaaa-4hwurl6y.localhost": ",GET-blaaa-4hwurl6y.localhost-%2Fapi%2Fshop%2Fget%2Ffirst-category"
```

and from that point onwards even tho the caddy log is still displaying:

```
Purging: blaaa-4hwurl6y.localhost
```
It only ever serves a cached response from `Request URL: http://blaaa-4hwurl6y.localhost/api/shop/get/` so at some stage keys are lost or the index loses track of some pages.

As this is pretty difficult to even reproduce is there any suggestions as to best way to track this down or good places to add log outputs to try help track whats happening? Ive already disabled saving STALE responses. Next I will try to disable saving { VARY } tags to see if thats whats causing the issue as thats my current suspicion.

**Comment by darkweak** [comment]
Can you paste your configuration? I think the last PR would fix that if you used nutsdb (`https://github.com/darkweak/souin/pull/224`)

**Comment by mattvb91** [comment]
Sorry havent been able to find any time yet to continue looking into this yet. My config currently:

```json
"cache": {
  "api": {
    "basepath": "/__cache",
    "souin": {
      "basepath": "/souin",
      "enable": true
    }
},
"cache_keys": {
  "/_next\\/static/": {
    "disable_host": true
  }
},
"cdn": {
  "dynamic": true,
  "strategy": "hard"
},
"distributed": true,
"log_level": "debug",
"nuts": {
  "path": "/tmp/nuts-souin"
},
"stale": "0s",
"ttl": "3600s"
},
```

Ive just tried running my CI on the commit `97a4664610606b7a6009af2902e6d1707fe4dd01` from the pull request above and the same problem still persists.

**Comment by mattvb91** [comment]
Hi @darkweak sorry about the delay, currently in hospital with an old macbook so its difficult / slow using docker on it but Ive made a start with a reproducible example.

Although in this case I didnt even get as far as the actually issue I had that caused me to create this issue but we can use this as a starting point to work through it.

https://github.com/mattvb91/caddy-cache-surrogates-bug

I hope the readme makes sense with what I am trying to do.

**Comment by darkweak** [comment]
Hey @mattvb91 I looked at your repository. It seems the targeted surrogate keys endpoint is not the good one. You're requesting `/__cache/souin/surrogate-keys` but that's `/__cache/souin/surrogate_keys`.

**Comment by mattvb91** [comment]
Oops my bad, will get a look again over the weekend and update hopefully with good reproducible

**Comment by mattvb91** [comment]
@darkweak I have just tried with the pull request above and still same issue. My current suspicion now is it must be getting lost in the round trip between different upstreams. In this case nextjs -> backend 

```json
{
   "handle":[
      {
         "handler":"headers",
         "request":{
            "delete":[
               "cache-control",
               "pragma"
            ]
         },
         "response":{
            "deferred":true,
            "delete":[
               "cache-control",
               "pragma",
               "server",
               "x-powered-by"
            ]
         }
      },
      {
         "allowed_http_verbs":[
            "GET"
         ],
         "default_cache_control":"no-store",
         "handler":"cache",
         "log_level":"debug"
      },
      {
         "handler":"subroute",
         "routes":[
            {
               "handle":[
                  {
                     "handler":"rewrite",
                     "strip_path_prefix":"/analytics"
                  },
                  {
                     "handler":"reverse_proxy",
                     "upstreams":[
                        {
                           "dial":"plausible:8000"
                        }
                     ]
                  }
               ],
               "match":[
                  {
                     "path":[
                        "/analytics/*",
                        "/api/stats/*",
                        "/api/event"
                     ]
                  }
               ]
            },
            {
               "handle":[
                  {
                     "handler":"reverse_proxy",
                     "transport":{
                        "protocol":"fastcgi",
                        "root":"/app/public/index.php",
                        "split_path":[
                           ""
                        ]
                     },
                     "upstreams":[
                        {
                           "dial":"laravel-api:9000"
                        }
                     ]
                  }
               ],
               "match":[
                  {
                     "path":[
                        "/api/*"
                     ]
                  }
               ]
            },
            {
               "handle":[
                  {
                     "handler":"reverse_proxy",
                     "upstreams":[
                        {
                           "dial":"nextjs-shop:3000"
                        }
                     ]
                  }
               ]
            }
         ]
      }
   ],
   "match":[
      {
         "host":[
            "testing.mavon.ie",
            "random-c6pspnyh.localhost",
            "{http.request.host}.localhost"
         ]
      }
   ],
   "terminal":true
}
```
