### ISSUE TITLE
Traefik (plugin) 2.6 & 2.7 support?

### ISSUE THREAD

**Issue by igoooor** [darkweak/souin#226]
I saw in another issue that Traefik is only supported for version before 2.6.
Any chance to see a support for more recent versions of traefik soon?

I know nothing about the breaking changes mentioned in that other issue, or how difficult they are to work around. So I am asking in a very friendly tone :)

**Comment by igoooor** [comment]
That would be amazing ♥️
I know oss can be time consuming, do you accept feature sponsoring?

**Comment by darkweak** [comment]
This commit should support the Træfik v2.7 https://github.com/darkweak/souin/pull/224/commits/5acb5770a2d439f0c90b0bdf5cc4ba6472d990a8 (I don't know why they continue to use their Yægi interpreter, this is really a pain).

**Comment by igoooor** [comment]
Looking forward for the merge :) ^^
Many thanks

**Comment by darkweak** [comment]
The `v1.6.11` should be available
