### ISSUE TITLE
Prevent authenticated users responses from being cached

### ISSUE THREAD

**Issue by darkweak** [darkweak/souin#247]
Actually, Souin doesn't follow the spec about the authenticated users. It caches responses that it shouldn't!

Implement in the `UpdateCacheEventually` method https://github.com/darkweak/souin/blob/master/rfc/bridge.go#L107

Fixes https://github.com/caddyserver/cache-handler/issues/34

**Comment by mattvb91** [comment]
How does one disable / enable this? I definitely need authenticated users to get cached responses however i would be nice to disable it on "admin" users for them to receive fresh responses all the time.

**Comment by darkweak** [comment]
We cannot handle a different cache strategy depending the authenticated user role. It's a business logic IMHO.

**Comment by mattvb91** [comment]
agreed, but i guess the question is how do you plan on implenting this on souin side then?

**Comment by darkweak** [comment]
An authenticated user (with either an `authorization` cookie or an `Authorization` header) can get a cached response, but cannot store a response related to an authenticated request unless the response explicitly allows it (more precisely it contains a public response directive).
