### ISSUE TITLE
Range header causes incomplete second request to be sent to backend

### ISSUE THREAD

**Issue by kresike** [darkweak/souin#249]
Latest souin release using caddy plugin.

The command ` curl -vs -r 0-524287 https://<hostname>/ `

causes the souin caddy plugin to return the following error

`ERROR   http.log.error  unsupported protocol scheme ""`

This is caused by a second roundtrip being triggered towards the backend, because range requests are hardcoded not to be cached.
When this second roundtrip happens, the req.URL is empty, meaning that there is no scheme or address to go to, and this causes the net/http package to error out with the message above.
My problem is, that I'm unable to discern what triggers the second roundtrip.

I forgot to mention, the response to the first roundtrip contains a response code of 206 and the associated partial content.

**Comment by darkweak** [comment]
Hello @kresike, I think that's in the `bridge.go`. We have a BaseRoundtrip and a Roundtrip functions. We can investigate together on that tricky bug if you want.
https://github.com/darkweak/souin/blob/2391f8372da6eae0ce559124d6c6838c2e0c10fe/rfc/bridge.go#L60
https://github.com/darkweak/souin/blob/2391f8372da6eae0ce559124d6c6838c2e0c10fe/rfc/bridge.go#L148

**Comment by kresike** [comment]
Yes, that is correct, however, I was trying to trace the call back to it's origins through the call stack and I'm unable to grasp why
` plugins.DefaultSouinPluginCallback.func3 ` is the source of the call (I know it's a goroutine spawned from somewhere but cannot find where it comes from.
![souin_bad_HTTP_call_02](https://user-images.githubusercontent.com/1885384/190199764-a16aba42-ef6e-4f2e-859d-159379e4c33f.png)
When this runs, the first roundtrip is already done, we have a response and the code knows that the response is not cacheable.

**Comment by darkweak** [comment]
IMHO we could remove the roundtrip part because souin is now mainly a middleware instead of a standalone project. We will move this part in the `souin middleware` itself.

**Comment by kresike** [comment]
The issue has been solved by @darkweak ! Thanks!
