### ISSUE TITLE
TTL from Cache-Control header of backend response

### ISSUE THREAD

**Issue by cdaguerre** [darkweak/souin#257]
Hi, is it possible to configure Souin (using the caddy plugin) to set the ttl from the `Cache-Control` header set by the backend?

**Comment by darkweak** [comment]
Hey @cdaguerre can you develop your issue?
Did you try to use Souin directly?

FYI I plan to merge the latest release in the cache-handler so if you have some weird behaviors I would be happy to fix them before the merge 🙂

**Comment by cdaguerre** [comment]
Hi @darkweak and thanks for your quick response:

This is an example of what I see:

| Header             | Value |
|----------------|-------------------|
| `Cache-Control` | `max-age=3600, public, s-maxage=3600` |
| `Age ` | `7` |
| `Cache-Status ` | `Souin; hit; ttl=113` |
| `Vary ` | `Accept` |

In this example, to my understanding, you can see the TTL set for the cached request is `120`, that it's already `7` seconds old and that it will remain in cache for `113` more seconds. 
I would expect it to be cached for as long as the `s-maxage` value states. 

This is what my `Caddyfile` looks like, nothing special, really....
```Caddyfile
{
    debug
    order cache before rewrite
    cache {
        default_cache_control no-store
    }
}

:443 {
    cache
  
    reverse_proxy nginx:80
}
````


Is this a bug or am I missing something?

**Comment by cdaguerre** [comment]
Arghh That makes sense. Could have figured that out by myself. RTFM ;)
Thank you very much for your help.
