### ISSUE TITLE
Memcached support

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [darkweak/souin#268]
https://github.com/bradfitz/gomemcache doesn't seem to have unsafe code (traefik plugin) and wouldn't be a bad addition as DragonFlyDB has support for memcached api and a couple more.

If you like the suggestion I could a PR with the implementation

**Comment by darkweak** [comment]
You can try that. You can try to build Træfik with your changes using `make build-and-run-traefik`

**Comment by darkweak** [comment]
We may reimplement the feature to list the keys https://github.com/bradfitz/gomemcache/pull/20/files

**Comment by darkweak** [comment]
FYI, I'm currently working on the memcache integration. I won't integrate that in the main distribution because the keys listing is not prod-ready and not acknowledged by the memcache maintainers team

**Comment by darkweak** [comment]
No, I'm using the original version because the grafana fork is not really well documented and doesn't have a good DX.

**Comment by darkweak** [comment]
Sadly yaegi is still running down with the error `CFG post-order panic: runtime error: invalid memory address or nil pointer dereference`. I appreciate if you can submit the issue on the yaegi github repository to make it more important to fix that. By the way you can say that I already tried to add the `// yaegi:tags purego` comment on top of the files to bypass that but without any successes.

**Comment by darkweak** [comment]
Cannot due to yaegi
