### ISSUE TITLE
Unable to get distributed cache to work in caddy plugin

### ISSUE THREAD

**Issue by cdaguerre** [darkweak/souin#270]
Hey @darkweak 
I've been trying desperately to get distributed cache storage to work.
I tried olric, etcd and redis and none of them work.
I created a [simple repository with docker-compose](https://github.com/cdaguerre/caddy-souin-distributed-cache) including containers for each of these 3 storage backends to play around with the souin configuration in the [Caddyfile](https://github.com/cdaguerre/caddy-souin-distributed-cache/blob/main/caddy/Caddyfile).
When none of them is active, http caching works as expected. But as soon as you enable one of the 3 storage backends, http caching stops to work.
Any advice or help would be much appreciated ;)

**Comment by cdaguerre** [comment]
Is it maybe due to the fact that there is no way of setting `distributed: true` in the caddy config?

**Comment by darkweak** [comment]
Unable to reproduce with the given global config
```
{
    order cache before rewrite
    {$DEBUG}

    cache {
        log_level debug

        olric {
            url 127.0.0.1:3320
        }
    }
}
```

**Comment by darkweak** [comment]
Can you try to increase the timeout directive please?
```
{
    order cache before rewrite
    {$DEBUG}

    cache {
        log_level debug
        timeout {
            backend 1s
            cache 1s
        }
        olric {
            url 127.0.0.1:3320
        }
    }
}
```

**Comment by cdaguerre** [comment]
Hey @darkweak, couldn't get it to work even with timeout settings.
I managed to get redis and etcd to work though. I added a load performance testing sccript ti run a benchmark. Here's what I get for a single url, 100 VUs, 500 iterations, 5 seconds

|                  | Hit ratio |
|------------------|-----------|
| Embedded olric   | 99 %      |
| External olric   | 0 %       |
| Etcd single node | 61 %      |
| Etcd cluster     | 50 %      |
| Redis            | 2 %       |

**Comment by darkweak** [comment]
The fact redis hit only 2%, etc 50% etc... is a real problem. And the fact I'm not able to reproduce is a real problem too.

**Comment by cdaguerre** [comment]
Have you tried to clone my repo and run the test?
Just in case:
```
git clone git@github.com:cdaguerre/caddy-souin-distributed-cache.git
cd caddy-souin-distributed-cache
CACHE=redis docker compose up -d
docker compose run --rm test
```
;)

**Comment by darkweak** [comment]
I'll give a try this evening 😉

**Comment by darkweak** [comment]
Got it! This condition was wrong https://github.com/darkweak/souin/blob/master/cache/providers/redisProvider.go#L115

**Comment by cdaguerre** [comment]
Not sure what this means, did you fix it somehow?

**Comment by darkweak** [comment]
Can you try to rebuild with 
```
    --with github.com/darkweak/souin/plugins/caddy@123300e224c34a49b30a380c5c8e90b1dc02d02a \
    --with github.com/darkweak/souin@123300e224c34a49b30a380c5c8e90b1dc02d02a
```?

**Comment by dkarlovi** [comment]
This might be related or not, but I'm seeing the same thing (cache never used, always misses), this is my Caddyfile:
```hcl
{
    auto_https disable_redirects
    order cache before rewrite
    log {
        output stdout
    }

}

storage:80 {
    log {
        output stdout
    }
    cache {
        allowed_http_verbs GET
        nuts {
            path /tmp
        }
        stale 1h
        ttl 24h
    }
    reverse_proxy https://upstream.s3 {
        header_up Host {upstream_hostport}
    }
}

:80 {
    root * /app/public
    file_server
    php_fastcgi app:9000
    log {
        output stdout
    }
}
```

When I run `caddy adapt`, I can see the config here was actually applied to `DefaultCache`, so it says:

```json
                            "DefaultCache": {
                              "allowed_http_verbs": [
                                "GET"
                              ],
                              "badger": {
                                "configuration": null,
                                "path": "",
                                "url": ""
                              },
                              "cache_name": "",
                              "cdn": {},
                              "default_cache_control": "",
                              "distributed": false,
                              "etcd": {
                                "configuration": null,
                                "path": "",
                                "url": ""
                              },
                              "headers": null,
                              "key": {
                                "disable_body": false,
                                "disable_host": false,
                                "disable_method": false
                              },
                              "nuts": {
                                "configuration": null,
                                "path": "/tmp",
                                "url": ""
                              },
                              "olric": {
                                "configuration": null,
                                "path": "",
                                "url": ""
                              },
                              "redis": {
                                "configuration": null,
                                "path": "",
                                "url": ""
                              },
                              "regex": {
                                "exclude": ""
                              },
                              "stale": "1h0m0s",
                              "timeout": {
                                "backend": "0s",
                                "cache": "0s"
                              },
                              "ttl": "24h0m0s"
                            },
                            "LogLevel": "",
                            "URLs": null
                          },
                          "nuts": {
                            "configuration": null,
                            "path": "",
                            "url": ""
                          },                          
                          "stale": "0s",
                          "timeout": {
                            "backend": "0s",
                            "cache": "0s"
                          },
                          "ttl": "0s"
                          
```

It seems the default cache is getting configured, but the values are not applied to my handler and might not be used at all.

I'm using the version suggested in https://github.com/darkweak/souin/issues/270#issuecomment-1305824811

Am I missing something here?

**Comment by darkweak** [comment]
I found the bug, the cache is not persisted if the cache directive is not specified in the global options.

**Comment by cdaguerre** [comment]
@darkweak I can confirm that commit https://github.com/darkweak/souin/commit/123300e224c34a49b30a380c5c8e90b1dc02d02a fixed redis in the benchmarks sent above and hit rate went up to 99%. 
Could you release?

**Comment by darkweak** [comment]
Yep I'll release in few hours! Thanks for testing and your feedbacks @cdaguerre

**Comment by darkweak** [comment]
Released 🚀
