### ISSUE TITLE
how to bypass when admin login?

### ISSUE THREAD

**Issue by shuaiZend** [darkweak/souin#271]
'regex' support cookie bypass full page cache?
hava some example?

**Comment by darkweak** [comment]
Hey @shuaiZend can you explain/develop your use case ?
The regex directive can only exclude the matched URL from being cached.

**Comment by shuaiZend** [comment]
> 
case: full page cache
example:
1.  guest user or spider browse cached pages
2.  logged user or admin browse uncache pages
