### ISSUE TITLE
Impossible to set value into Badger (Caddyserver)

### ISSUE THREAD

**Issue by eidenschink** [darkweak/souin#284]
Hi,

seconds after going live with a site Caddyserver with modules cache v0.3.0 and http.handlers.cache v0.3.0 exitted with the following message in the runtime logs:

`http.handlers.cache     Impossible to set value into Badger, Value with size 3354930 exceeded 1048576 limit. Value:`

Restarting the server was impossible (maybe it tried to resume an existing cache?) until I added a minimal Badger configuration with a double default MemTableSize like this:

```
        order cache before rewrite
        cache {
               allowed_http_verbs GET HEAD
               headers Content-Type Authorization Last-Modified
               stale 20s
               ttl 10s
               default_cache_control public
               # added after the exits:
               badger {
                       configuration {
                               MemTableSize 8388608,
                       }
               }
       }
```

Because I don't know when this will happen again I deactivated the cache for now. Do you have any idea what could cause this problem? Shoudn't it free memory itself as needed?

**Comment by darkweak** [comment]
Hello @eidenschink I suggest to use the latest souin release to get the fix. It doesn't crash anymore if the put runs into an error.

**Comment by eidenschink** [comment]
Hi @darkweak! Thanks for the tip!
I initially added it with `caddy add-package github.com/darkweak/souin/plugins/caddy github.com/caddyserver/transform-encode` and already did a `caddy upgrade` before writing this issue.
Do I have to explicitely add a release number or hash to get the latest release?

**Comment by eidenschink** [comment]
I removed the caddy module yesterday and switched to the latest Souin dev version. I started to test it under load on a production server today.

One question I forgot to ask: Why did Souin cache prohibit caddy to restart? After crashing caddy the mentioned error message showed up during the restart, stopped the server and systemd stopped after the foo-fast-restart error cycles. What is it that a fresh restart could not solve?

**Comment by eidenschink** [comment]
Maybe the restart problem is around the Badger storage. I assumed it is in-memory only. But it tries to mkdir a directory to persist data.
Additionally Souin cache seems to stop Caddy starting if it can't mkdir.
- could it be configured in-memory only?
- could it fall back to be in-memory only when data dir is not create- or writable?
