### ISSUE TITLE
Does cache-status expose too much in cf276b013b9 ?

### ISSUE THREAD

**Issue by eidenschink** [darkweak/souin#285]
Hi, in the latest cf276b013b9 "cache-status" exposes the cache-key along with the reason for the exact miss.

What was the reason to include the key=... by default?

As it is no problem to turn the header off or on selectively at least in Caddyserver, I wonder if the cache key (or both infos) should be private by default.

At least it would make cache busting for troublemakers not so easy.

**Comment by eidenschink** [comment]
Ok, after further reading: https://www.rfc-editor.org/rfc/rfc9211.html#name-the-key-parameter

"To avoid assisting such attacks, the Cache-Status header field can be omitted, only sent when the client is authorized to receive it, or sent with sensitive information (e.g., the key parameter) only when the client is authorized."

I guess i will just prepare a matcher for caddy that responds only to requests from certain IPs.

**Comment by darkweak** [comment]
Hello @eidenschink, I think I can add a boolean configuration entry to enable the key in the `Cache-Status` directives.
I will add this change in the #283

**Comment by eidenschink** [comment]
Hey @darkweak, great, thank you. I started a test of the commit before that this morning on a production server under a good amount of load where I restrict output to my IP. I'll give the new one a try tomorrow.

**Comment by darkweak** [comment]
It should work using this commit `13ab852f20c75b2256257fb0a6d0e3bdb1685a71`
`xcaddy build --with github.com/darkweak/souin/plugins/caddy@13ab852f20c75b2256257fb0a6d0e3bdb1685a71 --with github.com/darkweak/souin@13ab852f20c75b2256257fb0a6d0e3bdb1685a71` and you'll be able to configure it using either the `key` or `cache_keys` directive

```
cache {
    key {
        disable_body
        hide
    }
}
```

**Comment by darkweak** [comment]
Done in #283
