### ISSUE TITLE
exclude regex ignored

### ISSUE THREAD

**Issue by tasiotas** [darkweak/souin#286]
Hi,

souin v1.6.24

I have such a directive in Caddy:

```
cache {
	regex {
		exclude .+dashboard
	}
}
```

When I visit page `https://local.website.com/dashboard`, I do get a cache hit or store.

This key gets hit/stored
`GET-local.website.com-/dashboard`

Am I using `regex.exclude` wrong, or is it being ignored?

Thank you

**Comment by tasiotas** [comment]
sure, here it is:

```
{
  # debug
  local_certs
	skip_install_trust
	order geo_ip first
	order cache before rewrite
	cache {
		log_level debug
		allowed_http_verbs GET
		ttl 100s
		api {
			souin
		}
		redis {
			url redis:6379
			DB 1
		}
	}
	servers {
		metrics
	}
}

# localhost
localhost:80 caddy:80 { # need to specity port for http
	handle /metrics {
		metrics
	}

	handle /souin-api* {
		cache # http://localhost/souin-api/souin
	}
}

# main domains
*.local.website.com, local.website.com {
	tls /certs/localhost.crt /certs/localhost.key

	# geoip
	geo_ip {
		db_path /geolite/GeoLite2-Country.mmdb
		trust_header X-Real-IP
		reload_frequency 7d
		override_country_code pl
	}
	header {
		X-COUNTRY-CODE {geoip.country_code}
	}

	# common files
	handle /common/* {
		file_server
	}

	# nuxt
	handle {
		reverse_proxy http://nuxt:3000
		cache {
			regex {
				exclude .+dashboard
			}
		}
	}

	# handle errors
	handle_errors {
		rewrite * /common/error.html
		templates
		file_server
	}
}
```

**Comment by darkweak** [comment]
regex directive is not handled in handler directives https://github.com/darkweak/souin/blob/master/plugins/caddy/httpcache.go#L655. I'll patch that today.

**Comment by tasiotas** [comment]
thank you,

Not sure if its related, but also I cannot set cache configuration per handler

```
# nuxt
handle {
	reverse_proxy http://nuxt:3000
	cache {
		redis {
			configuration {
				Addr redis:6379
				DB 2
			}
		}
		ttl 600s
		allowed_http_verbs GET
	}
}
```

1. I can override ttl set in global options via handler directive
2. But not redis config. This handler is writing to redis DB 1, instead of 2. I tried to remove redis config from global options and define it only in handler, it got ignored completely, nothig was written to redis.

I can open separate issue if it's not related.

Thank you

**Comment by darkweak** [comment]
This commit will patch your issue https://github.com/darkweak/souin/pull/283/commits/1d6bff4ccdf8ccc0c1daf0d29098432bd72a6c43

**Comment by darkweak** [comment]
FYI, the redis configuration parser was not good because I forgot the caddyfile unmarshaler just take the key and treat end values (inside the directives) as string.

**Comment by darkweak** [comment]
You can try the fix using `xcaddy build --with github.com/darkweak/souin/plugins/caddy@1d6bff4ccdf8ccc0c1daf0d29098432bd72a6c43 --with github.com/darkweak/souin@1d6bff4ccdf8ccc0c1daf0d29098432bd72a6c43`

**Comment by tasiotas** [comment]
hi darkweak,

regex exclude still isn't working on [1d6bff4ccdf8ccc0c1daf0d29098432bd72a6c43](https://github.com/darkweak/souin/commit/1d6bff4ccdf8ccc0c1daf0d29098432bd72a6c43) nor [99ee0df105557ae8e013102f4a1ced02ccf61796](https://github.com/darkweak/souin/commit/10fc86b3c7d9a39be9518f5b67e9bb61e39aa06a).

I have a feeling you fixed the second issue I mentioned in this post (redis config parser), but the original issue of regex exclude was forgotten.

**Comment by darkweak** [comment]
I'm sorry I saw that. I'm working on it and work also on a merge for the configuration parsers. Every global cache directives will be usable in handlers with that. 
I plan to release that this evening

**Comment by darkweak** [comment]
Hello @tasiotas can you try with the hash 15f42bab3be9a06d141ebc4520403371037c2f59 please?

**Comment by tasiotas** [comment]
all good now, excluded routes respond with:

```cache-status: Souin; fwd=uri-miss; key=; detail=CANNOT-HANDLE```

thank you
