### ISSUE TITLE
accept-language causes uri-miss

### ISSUE THREAD

**Issue by tasiotas** [darkweak/souin#288]
Hi,

Caddy 2.6.2 build with
```
--with github.com/darkweak/souin/plugins/caddy@088682f2d19ea4fe5fb8df9a4c8b6e2903216054 \
--with github.com/darkweak/souin@088682f2d19ea4fe5fb8df9a4c8b6e2903216054
```

I have a request that is not being hit by cache, and looks like its caused by one specific header.

this works fine
`curl -d '{"email":"foo@bar.com"}' -H "Content-Type: application/json" https://website.com/api/accounts/check-email`

response:
```
< HTTP/2 200 
< age: 352
< allow: OPTIONS, POST
< alt-svc: h3=":443"; ma=2592000
< cache-status: Souin; hit; ttl=19648; key=POST-local.vfxtricks.com-/api/accounts/check-email-3c0ec8cfacbfb408798cd0001f35c67db5301893f5d325ef941023df79390a6b
< content-language: en
< content-type: application/json
< cross-origin-opener-policy: same-origin
< date: Fri, 16 Dec 2022 21:15:57 GMT
< referrer-policy: same-origin
< server: Caddy
< vary: Accept, Accept-Language, Cookie, Origin
< x-content-type-options: nosniff
< x-country-code: pl
< x-frame-options: DENY
< content-length: 21
```

but this request doesnt return cached value
`curl -d '{"email":"tas@tas.com"}' -H "Content-Type: application/json" -H "accept-language: en-US,en;q=0.9" https://local.vfxtricks.com/api/accounts/check-email -kv`

response:
```
< HTTP/2 200 
< allow: OPTIONS, POST
< alt-svc: h3=":443"; ma=2592000
< cache-status: Souin; fwd=uri-miss; stored
< content-language: en
< content-type: application/json
< cross-origin-opener-policy: same-origin
< date: Fri, 16 Dec 2022 21:23:07 GMT
< referrer-policy: same-origin
< server: Caddy, Werkzeug/2.2.2 Python/3.10.9
< vary: Accept, Accept-Language, Cookie, Origin
< x-content-type-options: nosniff
< x-country-code: pl
< x-frame-options: DENY
< content-length: 21
```

The only difference in request is `-H "accept-language: en-US,en;q=0.9"`, does that ring any bell?
Both requests result in cache storing key/values in cache backend.

Thank you

**Comment by darkweak** [comment]
I think that's the vary parser, I'll have a look at that in an hour.

**Comment by darkweak** [comment]
Indeed that's it
```
strings.Join(headers, ";")
```

I think I have to encode the header value or chose another varied headers separator because actually it generate a string like that `{-VARY-}foo:bar;accept-language:en-US,en;q=0.9`.

**Comment by tasiotas** [comment]
sorry, but that didn't fix the issue. semicolon is still causing problems in request's headers.

Im on 
```
RUN xcaddy build \
    --with github.com/darkweak/souin/plugins/caddy@10fc86b3c7d9a39be9518f5b67e9bb61e39aa06a \
    --with github.com/darkweak/souin@10fc86b3c7d9a39be9518f5b67e9bb61e39aa06a
```

**Comment by darkweak** [comment]
Hello @tasiotas can you try with the hash `15f42bab3be9a06d141ebc4520403371037c2f59` please?

**Comment by tasiotas** [comment]
yup, all good now, thanks!

**Comment by tasiotas** [comment]
hi,
I found another case where headers are breaking caching.

`curl -X POST -d '{"email":"foo@bar"}' -H "Content-Type: application/json" -H "Origin: https://website.com" https://website.com/api/accounts/check-email `

generates key:
`"/api/accounts/check-email-application/json-{-VARY-}Accept:*/*;Accept-Language:;Cookie:;Origin:https://website.com"`

resulting in `cache-status: Souin; fwd=uri-miss; stored` without ever `hit`

Without `-H "Origin: https://website.com"` it works fine.

Thanks

**Comment by darkweak** [comment]
I think I have to escape also when the header value contains a colon (`:`) too.

**Comment by tasiotas** [comment]
could you reopen this issue so it doesn't get lost?
thank you
