### ISSUE TITLE
flushing multiple Redis DBs

### ISSUE THREAD

**Issue by tasiotas** [darkweak/souin#292]
Hi,

Given config below, when I send PURGE request to souin API at /flush, I only get DB 0 cleared, not both 0 and 1.

If I remove redis.url from global cache declaration, nothing gets flushed. I guess PURGE calls default cache backend.

thank you

Caddyfile
```
{
  debug
  order cache before encode
  cache {
    log_level debug
    ttl 20000s
    api {
      souin
    }
    redis {
      url redis:6379
    }
  }
}

website.com {

  # django apis
  handle /api* {	
    cache {
      redis {
        configuration {
          Addr redis:6379
	  DB 1
	}
    }
    reverse_proxy http://django:8000
    }
  }

  # nuxt
  handle {	
    cache {
      redis {
        configuration {
          Addr redis:6379
	  DB 0
	}
    }
    reverse_proxy http://nuxt:3000
    }
  }
}
```

**Comment by darkweak** [comment]
I think you have to purge using `/api/{souin-api basepath}/{souin path}/flush` because your `/api*` handler define a different redis db.

**Comment by tasiotas** [comment]
oh I see, ill try and report back

**Comment by tasiotas** [comment]
yup, that worked.
I had to specify api endpoint per cache handler

thanks
