### ISSUE TITLE
cookies in key

### ISSUE THREAD

**Issue by tasiotas** [darkweak/souin#295]
Hi,

Not sure if its a bug or feature, but its bit concerning.

When I inspect keys in Redis, I can see that cache keys have plenty of client cookies. Is that necessary?
Key is longer then value itself, might bloat cache memory, plus `csrf`, `sessionid` and others might be security risk.

example:
```
"/apiql{-VARY-}Cookie:csrftoken%3DZeLs5WmoxI3MfiaCco0cj5ZSqKuiKXTBJ2IxLx8o4spCxuOVQ4GR7iQ6tKebH3us%3B+amplitude_id%3DeyJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOm51bGwsImxhc3RFdmVudFRpbWUiOm51bGwsImV2ZW50SWQiOjAsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjowfQ%3D%3D%3B+amplitude_id_eb9e4621db21faf713ee50c637f3cf36%3DeyJkZXZpY2VJZCI6ImEwYWNhNDhmLTRiMjktNGQyNC1iMzYyLWE2YmZmODc1M2QyOFIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTY3MjIwODAyOTExMiwibGFzdEV2ZW50VGltZSI6MTY3MjIwODY1MTU0OSwiZXZlbnRJZCI6MCwiaWRlbnRpZnlJZCI6MCwic2VxdWVuY2VOdW1iZXIiOjB9%3B+sessionid%3Dw9cjd8doi2sczz5jhg36yu1kmjdcyo09;Accept-Language:en-US%2Cen%3Bq%3D0.9;Origin:"
```

thank you

**Comment by darkweak** [comment]
Hello @tasiotas, your upstream returns a vary headers containing Cookie, Origin so we have to store these request header values on the key.
The Souin api must not be public and be placed behind a proxy authentication (Caddy matchers and basicauth).

**Comment by tasiotas** [comment]
oh, its all make sense now. I didn't know what is Vary header, after reading some MDN its all clear. 

thanks!
