### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by tasiotas** [darkweak/souin#296]
Hi,

I noticed this strange memory consumption with cache enabled.

Caddyfile:
```
{
  order cache before rewrite
  cache
}

website.com:80 {
  handle {
    cache
    respond "hello"
  }
}
```

When I test it with wrk (wrk2 to be specific), I get memory spike until I run of memory in container ( I limit it to 1GB)
`wrk -t2 -c1000 -d5m -R3000 http://website.com`

![bad](https://user-images.githubusercontent.com/9046931/210312201-f55b6334-4cad-40b3-b628-d5339fb6fc79.jpg)

This memory spike happens almost every time, every now and then it doesn't happen, or I dont wait long enough. Otherwise it happens after 10-20sec after starting stress testing.

Without cache enabled, I get constant 50MB memory usage.

I run it without metrics and TLS to eliminate other causes. Graphed with [this ](http://www.zakariaamine.com/2019-12-04/monitoring-docker/)method 

thank you

**Comment by tasiotas** [comment]
which commit should I try?

with f6c71a2907db087c109bfd76c10c515633d9809a it stopped working with Redis as backend.

**Comment by darkweak** [comment]
What's the configuration?  
What do you get as response headers?

**Comment by tasiotas** [comment]
sorry, I spoke too soon. It does work fine, no more OOM crashes. 
thank you

I am no sure if this update introduced performance regression (couldn't stress test it before because of OOM) but here are my findings.

![image](https://user-images.githubusercontent.com/9046931/211184229-251c4e57-a624-45f3-886e-5939c95f53a2.png)

1. Redis 300 req/s
2. Badger 1200req/s
3. Without caching 7500req/s

I am testing with simple `respond "hello"` directive. I understand it doesn't capture real world usage.
Is this expected cost of using caching in Caddy?

**Comment by darkweak** [comment]
I'll run the stress test and profile it

**Comment by darkweak** [comment]
Can you tell me how you generate your graph please?

**Comment by tasiotas** [comment]
Prometheus grabs metrics from Caddy, Grafana makes graphs

**Comment by darkweak** [comment]
Hey @tasiotas the memory footprint must be lower now.

**Comment by tasiotas** [comment]
yep, memory is fine. thanks
