### ISSUE TITLE
How to compile or build RPM of Souin for EL9

### ISSUE THREAD

**Issue by skrlance** [darkweak/souin#312]
It feels good for me to see that Souin cache is trending because of Caddy! I see that Caddy 2 is available to install on Enterprise Linux distros, and for WordPress it would be best to use Caddy along with Souin.
Caddy has a plugin available to integrate to the Souin cache. However, how do we compile darkweak Souin to use it in EL9?
Is it possible for you to keep .spec file at-least so we can compile easily?

**Comment by darkweak** [comment]
Hello @skrlance to be honest I don't know how to do that. If you can use xcaddy, you can run `xcaddy build --with github.com/darkweak/souin/plugins/caddy` and it will create a caddy binary that you can run and you don't have to compile Souin itself.
