### ISSUE TITLE
Custom key generation

### ISSUE THREAD

**Issue by frederichoule** [darkweak/souin#318]
Is there any way to customize the key generation? I see that we can disable_body, disable_method, but is there any way to build the key format we really want?

For example, I have one use-case where I need to strip out query paramters from the key.

I open the issue here, but i'm really using https://github.com/caddyserver/cache-handler instead.

**Comment by frederichoule** [comment]
Alright, I'll do it today.

**Comment by frederichoule** [comment]
Doing some work here https://github.com/darkweak/souin/pull/319

**Comment by darkweak** [comment]
Closed by #319
