### ISSUE TITLE
cache_keys order

### ISSUE THREAD

**Issue by frederichoule** [darkweak/souin#330]
In what order `cache_keys` are handled?

I am trying to achieve:
- `/.*`: `disable_query true`
- `/?something=1`: `disable_query false`

I tried with this configuration, but it doesn't work:
```
cache_keys {
	".*" {
		disable_query true
	}
	".*\?something=1$" {
		disable_query false
	}
}
```

**Comment by frederichoule** [comment]
Well, I thought I had tried it, but just switching them works, since there's a break as soon as it finds a match. https://github.com/darkweak/souin/blob/master/context/key.go

**Comment by frederichoule** [comment]
I am reopening this since https://github.com/darkweak/souin/pull/331 will fix it.

So yes I had switched the keys and it worked, but it had other unexpected consequences. I switched to `matchers` in Caddy instead of `cache_keys`, but as soon as released I'll try again and see if there are any more bugs.

**Comment by darkweak** [comment]
You can already try it using `xcaddy build --with gitHub.com/darkweak/souin/plugins/caddy@${HASH} --with gitHub.com/darkweak/souin@${HASH}` where `hash` is the commit hash
