### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Darkweak** [Darkweak/Souin#34]
Provide a REST API to be able to :
- Get cache keys
- Get cache value from key
- Use BAN/PURGE HTTP methods
- Clear keys by regexp

API will be accessible with or without JWT depending your configuration

**Comment by PureKrome** [comment]
I was just popping in here to learn if there was an API for this.

MY USE CASE: I use aggressive caching for GET requests (lets say a day or a week) but when the (hardly ever changing content) does change, I can send an "internal" HTTP PURGE request to the Cache and that GET cache key is now purged. next request will MISS and then get the most current results from our website/webapi/etc.

**Comment by Darkweak** [comment]
@PureKrome It's now merged and it works like a charm
