### ISSUE TITLE
Add support for Cache Invalidation and Cache Groups Internet Drafts

### ISSUE THREAD

**Issue by dunglas** [darkweak/souin#355]
There is now I-D for these features:

* https://datatracker.ietf.org/doc/draft-nottingham-http-cache-groups/
* https://datatracker.ietf.org/doc/draft-nottingham-http-invalidation/

**Comment by darkweak** [comment]
Hello, thanks for sharing, TBH I wont have time to work on this integration until the next month. It's not a high priority because that's a very recent draft RFC and it may change a lot before being accepted.
