### ISSUE TITLE
Dumping cached responses into log on default log level

### ISSUE THREAD

**Issue by ueffel** [darkweak/souin#361]
I don't think it's a good idea to log complete response on INFO log level.

* <https://github.com/darkweak/souin/commit/a3d23bc8eb9446b334d6ee34e692ffda308e6164#diff-5b6d6847c385671f06ecd44295ce5691596b68f54f3aeee404691bb09779be1eR421>
* <https://github.com/darkweak/souin/commit/a3d23bc8eb9446b334d6ee34e692ffda308e6164#diff-5b6d6847c385671f06ecd44295ce5691596b68f54f3aeee404691bb09779be1eR237>

I'm using souin as caddy module and wondered why logs contains so much binary data (cached images). I see that it may be good on DEBUG log level but on INFO level. Please consider reverting the linked changes.

**Comment by darkweak** [comment]
Hey @ueffel that's taken in consideration in the #359. I plan to tag the new release this week.
