### ISSUE TITLE
New NutsDB?

### ISSUE THREAD

**Issue by ueffel** [darkweak/souin#364]
Are there any plans to update to the newer NutsDB dependency?  
I'm not thinking about anything specific thas new in nuts. Just the project seems to be quite active since the module name changed from `github.com/xujiajun/nutsdb` to `github.com/nutsdb/nutsdb` and souin is 3 minor versions behind :)

**Comment by darkweak** [comment]
Hey @ueffel of course, I have to write a little fix to about the RFC implementation, so I can wrap the NutsDB bump (and also bump other storages). It should be done at the end of the week.
