### ISSUE TITLE
Add support for in-memory NutsDB

### ISSUE THREAD

**Issue by zx8** [darkweak/souin#409]
Since [v0.7.0](https://github.com/nutsdb/nutsdb/releases/tag/v0.7.0), NutsDB has supported in-memory storage.

Looking through the [configuration parsing code for NutsDB](https://github.com/darkweak/souin/blob/b4b25aa352b6df8c1b4ae534d7c3881beb3866f1/plugins/caddy/configuration.go#L450-L467) for Caddy, it seems that Souin does not yet support an in-memory option.

Is this an option you might consider adding?

Thank you!

**Comment by darkweak** [comment]
Hello, @zx8 thank you for pointing out this feature. We will be able to replace badger default storage by nutsdb in memory with that! 👍
