### ISSUE TITLE
public,max-age=31536000, immutable

### ISSUE THREAD

**Issue by enricoschaaf** [darkweak/souin#424]
Hi 👋

I am using Souin through Caddy and I noticed that a public,max-age=31536000, immutable cache control response header from the origin gets cached for 120 seconds (the default ttl) instead based on the max age?

Is this a bug or something that can be configured?

Thanks for providing a way to run a cache alongside caddy :)

**Comment by darkweak** [comment]
Hello @enricoschaaf sorry for this long time without answer.

I think that's a bug, I put your issue on my debug-todo list. Maybe I could write a patch this weekend but not guaranteed.

Thank you for your feedback, I keep you updated on that.

**Comment by darkweak** [comment]
@enricoschaaf We store the response for the `min` between `max-age` response directive and the `ttl` defined in the configuration (default `120s`). A solution could be to increase the default `ttl` directive but I'm wondering if we have to keep the actual behavior or remove this duration calculation. I don't think the rfc specifies something about that.
