### ISSUE TITLE
Nginx / apache example

### ISSUE THREAD

**Issue by fliespl** [darkweak/souin#426]
Description mentions I can use it with those, but can't find any example. Is there one? Should nginx proxy to suohin and fallback to main proxy?

Works like w charm with Caddy though.

**Comment by darkweak** [comment]
Hello @fliespl you can use the standalone server to have a cache server working with Apache/nginx or build a custom module that embed Souin and load it in the proxy. I plan to write some documentation to explain each cases 

Thank you for your feedback 🙏

**Comment by fliespl** [comment]
Thank you very much - appreciate it! Keep up the great work!
