### ISSUE TITLE
Better explanation on mode option

### ISSUE THREAD

**Issue by fliespl** [darkweak/souin#428]
It would be great, if there were precise descriptions how each mode behaves. 

Currently it's more like trial & error on my part, but feels like "bypass_request" is the way to go, if I simply want to ignore cache-control / pragma (devtools mode) from the user.

**Comment by darkweak** [comment]
Hey @fliespl Indeed it's difficult to understand what does each directives without the background of this discussion https://github.com/darkweak/souin/issues/345 (more precisely this comment https://github.com/darkweak/souin/issues/345#issuecomment-1560574770). I'm currently writing a documentation website (https://github.com/darkweak/souin/tree/feat/documentation/website/souin-documentation) to reduce the lack of explanations, have some use cases, concrete examples, ....
