### ISSUE TITLE
order cache before rewrite - question

### ISSUE THREAD

**Issue by fliespl** [darkweak/souin#440]
I would like to strip known marketing query string parameters. On varnish I would use something like following.

```
if (req.url ~ "(\?|&)(gclid|utm_[a-z]+)=") {
    set req.url = regsuball(req.url, "(gclid|utm_[a-z]+)=[-_A-z0-9+()%.]+&?", "");
    set req.url = regsub(req.url, "[?|&]+$", "");
}
```

With caddy I can use internal rewrite rule.

The question is: since manual tells me to set mentioned setting (cache before rewrite) - will it work? Or will souin look for cache key with those query strings?

**Comment by darkweak** [comment]
Hey @fliespl if you want to strip some parts of the url, the cache system will consider `domain.com/page?q1=foo@q2=bar` and `domain.com/page?q1=baz` equal because it will receive only `domain.com/page` as url (due to stripped).
