### ISSUE TITLE
Fail to build with go < 1.21

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [darkweak/souin#458]
```
#47 0.477 /build/golang-current/source/pkg/mod/github.com/darkweak/souin@v1.6.46/pkg/middleware/middleware.go:9:2: package maps is not in GOROOT (/build/golang-current/go/src/maps)
#47 0.477 /build/golang-current/source/pkg/mod/github.com/darkweak/souin@v1.6.46/pkg/rfc/vary.go:7:2: package slices is not in GOROOT (/build/golang-current/go/src/slices)
```

Looks like https://github.com/darkweak/souin/commit/678a1dbb22f0231ed220eaf02fdf1abe69e9edb5 introduced dependencies to the go lib that are only available starting with 1.21, but somehow did not update go.mod to reflect that (which still indicates go 1.19).

Hope I am not mistaken here.

Thanks!

**Comment by darkweak** [comment]
Hello @dubo-dubon-duponey I thought I updated the `go.mod`, will be fixed in the next release.
