### ISSUE TITLE
Separate cache entry is created for Safari browser

### ISSUE THREAD

**Issue by Shotster** [darkweak/souin#519]
I'm using Souin as a Traefik v3 plugin with Docker.

I've noticed that a different cache key (and thus a separate cache entry) is created for Safari browser. It seems to be related to a difference in the `Accept-Encoding` header (Safari doesn't have "zstd" in that header). I didn't realize the `Accept-Encoding` header was used as part of the key.

It's unclear if this is intended behavior. Is there a way to tell Souin to ignore that header for cache key purposes? I'd prefer to have a single cache entry regardless of browser used.

### Cache keys after visiting page with Chrome, Firefox, or other Chromium browser...
```
[
  "SURROGATE_STALE_",
  "STALE_SURROGATE_STALE_",
  "SURROGATE_",
  "STALE_SURROGATE_",
  "GET-https-website.co-/api/1.1/wf/assets{-VARY-}Accept-Encoding:gzip, deflate, br, zstd",
  "STALE_GET-https-website.co-/api/1.1/wf/assets{-VARY-}Accept-Encoding:gzip, deflate, br, zstd"
]
```

### Cache keys after visiting page with Safari...
```
[
  "SURROGATE_STALE_",
  "STALE_SURROGATE_STALE_",
  "SURROGATE_",
  "STALE_SURROGATE_",
  "GET-https-website.co-/api/1.1/wf/assets{-VARY-}Accept-Encoding:gzip, deflate, br",
  "STALE_GET-https-website.co-/api/1.1/wf/assets{-VARY-}Accept-Encoding:gzip, deflate, br"
]

```

**Comment by Shotster** [comment]
So I realized after posting this issue that I could work around it by using another Traefik middleware to rewrite the `Accept-Encoding` request header so the upstream server gets a consistent value regardless of browser. It works, but I'd still like to know if behavior I've noted is intended or if there's a way to disable it.

**Comment by darkweak** [comment]
Hello @Shotster, I don't have deserialization/normalization for headers so if your `Accept-Encoding` differs from a browser to another, I can't serve the same response (because `Accept-Encoding` is returned in the `Vary` response header).

**Comment by Shotster** [comment]
Ok, thanks for the prompt response. I guess I'll close this out and do some research to better understand.

**Comment by darkweak** [comment]
But I'm wondering if the coalescing system will sen only one request to the backend if an authenticated user and an anonymous user try to send the request on the same endpoint (just having an `Authorization` HTTP request header on the authenticated user). I'll have to do some tests. I'm re-opening to keep it on my todo.
