### ISSUE TITLE
Update Nutsdb to latest version 1.0.4

### ISSUE THREAD

**Issue by adammakowskidev** [darkweak/souin#521]
Hi
I see that Souin is currently using nutsdb version 0.14.3, currently the latest version is 1.0.4 and it looks like a stable release and fixing many bugs. Nuts is one of the few engines that is very efficient and works well.

https://github.com/nutsdb/nutsdb/releases

@darkweak can we hope on an upgrade? :)

Regards

**Comment by darkweak** [comment]
hey @adammakowskidev it will take some time to bump the nuts version because they changed their API so actually I can't use it to list the keys. I'm trying to find a workaround for that but I can't tell you how many time it will take to be done.

**Comment by adammakowskidev** [comment]
@darkweak Thank you for your reply.
