### ISSUE TITLE
Caddy container in k8s is reaching its memory limit because cache fills up the memory

### ISSUE THREAD

**Issue by yuvalman** [darkweak/souin#529]
While utilizing the middleware https://github.com/caddyserver/cache-handler in Caddy pod that runs on k8s,

 I experimented with both Badger and NutsDB providers.

I conducted a load/stress test to see if the memory fills up and validates whether the old cache is removed (prior to triggering a container restart), possibly utilizing an LRU or other strategic approach (as described in this issue: https://github.com/darkweak/souin/issues/140). However, this didn't prevent the cache from filling up.

Does anyone have any suggestions on how we could delete old resources from the cache?

this is the current cache configuration:

      cache {
        nuts {
          configuration {
              Dir /tmp/nuts-configuration
              EntryIdxMode HintKeyValAndRAMIdxMode
              RWMode 0
              SegmentSize 1024
              NodeNum 1
              SyncEnable true
              StartFileLoadingMode 1
          }
        }
        cache_name Files-Cache
        log_level debug
        ttl 300s
        key {
          disable_body
          disable_host
          disable_method
          disable_query
          hide
        }
        mode bypass_request
      }

**Comment by darkweak** [comment]
Hello, sorry for the long delay. I think the issue should be opened in the nutsdb repository because I don't have the lead to handle the max memory limit in the storage (if the storage doesn't allow to limit the size or if it doesn't work as expected). You can list the max size per response using the `max_body_bytes` directive in the Souin / cache-handler configuration (but as said that's per responses, not for the whole storage).

**Comment by yuvalman** [comment]
Thanks @darkweak,
In case of using badger, how do you suggest to make the invalidation of the cache?
If the cache filled up to it's maximum, how the cache suppose to clean the old attributes in it?
Does it done using LRU strategy? Is it also related to provider (Badger/NutsDB) configuration or is it related to Souin logic/configuration (as described in issue: https://github.com/darkweak/souin/issues/140#issuecomment-945627922)?

**Comment by darkweak** [comment]
@yuvalman Badger and NutsDB should use the LRU eviction by default.  
If you want to invalidate the cache you can use the api provided by Souin itself (by default on the endpoint `/souin-api/souin`).
