### ISSUE TITLE
Testing : cache interoperability test to pass https://cache-tests.fyi/#expires 

### ISSUE THREAD

**Issue by gedw99** [darkweak/souin#535]
https://cache-tests.fyi/#expires

worth getting Sousin validated and published there  or elsewhere ? 

looks like the test are already here: https://github.com/darkweak/souin/blob/master/docs/cache-tests/index.mjs ?

**Comment by darkweak** [comment]
Hey @gedw99 the cache-tests only tests the `cache-handler` (that is Souin under the hood) so we don't need to add Souin there.  
About the `expires` section, I'm including this in the issue #536

**Comment by darkweak** [comment]
@gedw99 If you need some support, just add me on discord sylvain7406.
