### ISSUE TITLE
Invalidate cache in default project api platform 

### ISSUE THREAD

**Issue by g-ra** [darkweak/souin#541]
There appears to be an issue with the cache invalidation process within our application. The cache is not being invalidated immediately upon data entry or modification, leading to outdated data being served to the users. This issue was observed and demonstrated in the following video: [Loom Video](https://www.loom.com/share/d3f0510ddc6244918243ea7a13e9a154).

**Steps to Reproduce:**

Enter or modify data in the application.
Check the cache to see if it has been invalidated.
Observe that the cache is still serving outdated data.
**Expected Behavior:**
The cache should be invalidated immediately upon any data entry or modification to ensure that users are always served the most up-to-date information.

**Actual Behavior:**
There is a noticeable delay between the data entry/modification and the cache invalidation, causing outdated data to be served.

**Questions:**

How much time typically passes before the cache is invalidated?
Is there a way to configure or influence the cache invalidation timing to ensure immediate updates?

Possible Solutions:

Investigate the cache invalidation logic to ensure it triggers immediately upon data changes.
Provide configuration options to set the cache invalidation timing.
Attachments:

[Link to the Loom video demonstrating the issue](https://www.loom.com/share/d3f0510ddc6244918243ea7a13e9a154)

**Comment by darkweak** [comment]
Hello @g-ra the commit `743a3a45f4f3d3509def3d2654c0a0eda1f49636` fixes that. You canary the patch with
```
    --with github.com/darkweak/souin/plugins/caddy@743a3a45f4f3d3509def3d2654c0a0eda1f49636 \
    --with github.com/darkweak/souin@743a3a45f4f3d3509def3d2654c0a0eda1f49636
```

**Comment by g-ra** [comment]
yeah, works fine
