### ISSUE TITLE
Cache Invalidation Issue for User Data in Bypass Mode

### ISSUE THREAD

**Issue by g-ra** [darkweak/souin#542]
Video: https://www.loom.com/share/b11e3e03f1d2469c8dddeb6880ea6b3f
Description:
We have encountered a problem related to cache invalidation when using the bypass mode. The issue arises under the following conditions:

User A performs a PATCH request to update the username for a specific user (e.g., PATCH /users/1).
User B concurrently accesses the user data through a GET request to the collection endpoint (e.g., GET /users).
Problem:
After User A updates the username, User B's cache is not invalidated, resulting in User B seeing outdated information when accessing the user list.

Questions:
Cache Behavior in Bypass Mode:
How is the cache expected to behave in bypass mode? Should the cache be invalidated automatically when a user data update occurs, or is this behavior considered normal?

Recommended Mode:
Is there a more appropriate caching mode that should be used to ensure that the cache is invalidated correctly, or do we need to implement a custom cache invalidation strategy in bypass mode?

Steps to Reproduce:
Authorize two users (User A and User B).
User A sends a PATCH /users/1 request to update the username.
User B sends a GET /users request to retrieve the list of users.
Observe that User B receives outdated data due to the cache not being invalidated.
Expected Behavior:
The cache should reflect the updated user data immediately after the PATCH request, ensuring that all users see the most current information.

Actual Behavior:
The cache is not invalidated after the PATCH request, leading to outdated information being shown to other users.
**upd** also cache invalidation does not occur for the user who made the changes

Suggested Solutions:
Review Cache Invalidation Policies:
Assess the current cache invalidation policies and determine if adjustments are needed for bypass mode.

Consider Alternative Caching Strategies:
Explore different caching modes or strategies that may be more suitable for this use case, ensuring that all users always have access to the most recent data.

Impact:
This issue can lead to inconsistencies in the data displayed to users, affecting the user experience and potentially causing confusion or errors.

**Comment by darkweak** [comment]
@g-ra @yuvalman @white-paprika @MyProfileX is it still relevant?

**Comment by darkweak** [comment]
Resolved by #545 #536
