### ISSUE TITLE
Help with debugging cache error with Redis

### ISSUE THREAD

**Issue by danielloader** [darkweak/souin#550]
Facing an interesting issue where _most_ of the requests I make are caching as expected, but one isn't, and I can't deduce why.

```
{"level":"error","ts":1726567415.6833787,"logger":"storages.cache.redis","msg":"Impossible to decode the key GET-REDACTED, proto: cannot parse invalid wire-format data"}
```

Which yields the expected header in the response of:

```
Cache-Status: "Souin; fwd=uri-miss; detail=REDIS-INSERTION-ERROR; key=GET-REDACTED"
```

But where do I go about debugging this further? I am using the caddy middleware approach here.

Interestingly the key is visible in Redis, with what looks to be the correct payload - hard to tell with all the non unicode characters in the value field but it looks similar to the expected json stored in the key.

Noticed that keys that work look like this:

<img width="614" alt="image" src="https://github.com/user-attachments/assets/2c75fe7e-befb-46f2-8bbc-76af72f11fdc">

Where as this misbehaving key has stored the header in the key as follows:

<img width="566" alt="image" src="https://github.com/user-attachments/assets/e66c99ab-bab6-4bf3-ab53-424677e3dd81">

I've tried various Accept-Encoding headers wondering if it's due to compression but ultimately can't work it out - any tips where to go next would be great!

**Comment by darkweak** [comment]
Hello @danielloader do you have some debug logs?
The value you're seeing is a protobuf encoded value FYI so that's why it's ugly. Did you try to reset the storage?

**Comment by danielloader** [comment]
Hello, I did enable debug log level on the cache middleware and don't actually get any additional log lines related as far as I can tell. I'll re enable it to be sure later.

I've tried deleting individual keys that seem to be poisoning the cache, setting a maximum key size (2MB) and I've done a full delete of the redis pod and pv to get a fresh cache persistence layer. 

Anything else I could try?

**Comment by darkweak** [comment]
@danielloader what's your config?

**Comment by danielloader** [comment]
```
{
	auto_https off
	order cache before rewrite
	cache {
		allowed_http_verbs GET HEAD
		log_level info
		max_cacheable_body_bytes 2097152
		api {
			prometheus
			basepath /_admin
		}
		mode bypass_request
		ttl 86400s
		redis {
			configuration {
				Addrs {$REDIS_HOST}:{$REDIS_PORT}
				Password {$REDIS_PASSWORD}
			}
		}
	}
	log {
		output stdout
		format json
		level {$LOG_LEVEL}
	}
}

# Health checks
:80 {
	respond /healthz 200
}

# Prometheus
:9090 {
	metrics /metrics
}

# Common options for vendors
(common) {
	log
}


:80 {
	import common

	cache {
		cache_name cache
		ttl 31536000s # 1 year redis side
        default_cache_control "max-age=86400" # 1 day browser side
	}

	reverse_proxy {
		to https://example.com:443
	}
}
```

Hoping the slightly simplified redacted config is useful, the actual reverse proxy gets headers injected for auth at this point and points to secure service.

**Comment by darkweak** [comment]
I wonder if that could be related to cloudflare. Can you try to request directly your server without going through cloudflare?
The `cannot parse invalid wire-format data` is thrown because the writer doesn’t write as many bytes as the reader reads bytes.
I assume that you used the `github.com/darkweak/storages/redis/caddy` module right?

**Comment by danielloader** [comment]
I've tried go-redis and redis modules just to rule out any client implementations, I'll try direct as you suggest by port forwarding to. the caddy instance directly and hitting it up with a curl. 
That said the upstream I am reverse proxying is hosted by cloudflare itself.

**Comment by darkweak** [comment]
@danielloader did you try with the latest release? (`github.com/darkweak/souin/plugins/caddy@v1.7.2`) first without redis and trying to add redis if that's working?

**Comment by danielloader** [comment]
I'll give it a shot tomorrow and get back to you.

**Comment by danielloader** [comment]
Interestingly I've just noticed after adding the Accept-Encoding header value to the key name I can see the original request which asks for `Accept-Encoding: gzip, br` then under it, the same key without a suffix but including the cache response header content - just the headers in the redis key below:

```
"Mdp�7
�LHTTP/0.0 200 OK
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONSL�Origin: *
Cachek�: max-age=86400
Content-Encoding: br�Type: application/json; Charset=UTF-8
Date: Wed, 16 Oct 2024 10:02:48 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: Caddy
X-Apilayer-TransQ�N-Id: 2c355a2e-7f49-4d6b-b714-6ef3153a8a0b
X-Request-Time: 0.006
X-Souin-Stored-Length: 2157���������vTtl: 24h0m0s
```

```
"Mdp��
�LHTTP/0.0 200 OK
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONSL�Origin: *
Cachek�: max-age=86400�2Status: api; fwd=uri-miss; stored; key=GET-http-api.9�.io-/v1/symbols-gzip, br
Content-Encoding:�Type: application/json; Charset=UTF-8
Date: Wed, 16 Oct 2024 10:02:48 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: Caddy
X-Apilayer-TransQ�N-Id: 2c355a2e-7f49-4d6b-b714-6ef3153a8a0b
X-Request-Time: 0.006
X-Souin-Stored-Length: 2157���������vTtl: 24h0m0s
```

Have no idea if it's relevant.

Given the issue seems very specific to me, I can potentially get you a reproduction setup and invite you to a private repository if you want to look.

**Comment by danielloader** [comment]
Okay good news, after some testing it seems to behave now. So that's good news!

The only issue I'm seeing is Vary (for Accept-Encoding) is not being included into the cache keys, it's a separate issue for sure but I don't know how to make sure the Accept-Encoding drift is covered in the cache so gzip responses aren't being issued to clients issuing `Accept-Encoding: br` requests.
