### ISSUE TITLE
add "deps" to make so we have xcaddy version consistent  ?

### ISSUE THREAD

**Issue by gedw99** [darkweak/souin#566]
Hey @darkweak 

Could we add a "deps" make target so that xcaddy is installed to the right version.

xcaddy and caddy are cross dependent and its just nicer to lock downtime versions of the 2 together.

Its the first thing I had to do to get doing with compiling off the make file to test things out.

**Comment by darkweak** [comment]
Hey @gedw99 basically you just have to install the caddy `latest` version. I don't understand the goal here.

**Comment by darkweak** [comment]
Thanks to go backward compatibility so if you have an higher version than the required one it will still work.
