### ISSUE TITLE
Configurable HTTP status code list for isCacheableCode

### ISSUE THREAD

**Issue by patramsey** [darkweak/souin#574]
Hello,

I have a use case where I would like to cache HTTP 301 and HTTP 302 responses. The list of cacheable response codes seems hard coded in isCacheableCode.

```
func isCacheableCode(code int) bool {
	switch code {
	case 200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501:
		return true
	}

	return false
}
```

I understand this list comes directly from the [RFC](https://datatracker.ietf.org/doc/html/rfc7231#section-6.1) . Would there be an appetite for a PR to make this list configurable for non standard use cases like mine?

**Comment by darkweak** [comment]
Hey @patramsey I can implement that in this tool, the PR should be ready on Monday. :)

**Comment by darkweak** [comment]
@patramsey can you try with the commit `aeb3b005ccb85d746dcd1770f61bb94ff60c2474` as target?

**Comment by patramsey** [comment]
@darkweak I was able to test out the changes in `aeb3b005ccb85d746dcd1770f61bb94ff60c2474` via some changes in https://github.com/caddyserver/cache-handler. I'm now getting a 
`Cache-Status: Souin; fwd=uri-miss; detail=UPSTREAM-ERROR-OR-EMPTY-RESPONSE; key=GET-http-127.0.0.1:8079-/two` 

when trying to cache an HTTP 302 I believe due to
```
func canStatusCodeEmptyContent(code int) bool {
	switch code {
	case 204, 301, 405:
		return true
	}

	return false
}
```

on [this](https://github.com/darkweak/souin/blob/master/pkg/middleware/middleware.go#L326) line

**Comment by darkweak** [comment]
@patramsey the fix is available using the commit `dec0714c1cf2bc36929ecea6c87b97c26a9bd594`. Sorry for the inconvenience.

**Comment by patramsey** [comment]
@darkweak working great in my testing!

```
curl -v http://127.0.0.1:8079/two
*   Trying 127.0.0.1:8079...
* Connected to 127.0.0.1 (127.0.0.1) port 8079
> GET /two HTTP/1.1
> Host: 127.0.0.1:8079
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 302 Found
< Age: 59
< Cache-Control: public, max-age=60
< Cache-Status: Souin; hit; ttl=1; key=GET-http-127.0.0.1:8079-/two; detail=DEFAULT
< Content-Length: 0
< Date: Fri, 15 Nov 2024 18:59:43 GMT
< Location: https://www.example.com/2
< Server: Caddy
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by patramsey** [comment]
@darkweak thanks again for implementing. Any thoughts on when this will be cut into a release?
