### ISSUE TITLE
remove a header from the cached object?

### ISSUE THREAD

**Issue by teodorescuserban** [darkweak/souin#587]
I have an edge case where I would like to remove a header from the response, but only if the response comes from cache.

Is this possible?

Thank you.

**Comment by darkweak** [comment]
Hello @teodorescuserban I think that's not possible, your use case is so specific because it's conditional.

**Comment by teodorescuserban** [comment]
Thank you for reply, @darkweak. I think I can remove the header with a matcher directly. I'll have to double check.
