### ISSUE TITLE
stupide question ^^ but important

### ISSUE THREAD

**Issue by lucmichalski** [Darkweak/Souin#60]
Hi @Darkweak ,

Hope you are all well !

So, I am looking for an alternative to varnish for caching content of some prestashop websites.

What is the state of **souin** vs **varnish** ? Do you plan to have an advanced config file for parsing cookies or headers for custom caching ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by Darkweak** [comment]
Hi @lucmichalski,

I'm fine and I hope you're all well too!

Thank you for your interest about Souin. It could be an interesting feature, but can you explain what do you want to do ? At the moment, you can compose the cache key with additional headers for each URL/regex you provide in the configuration file and this way you can set a different ttl for each matching request incoming. Maybe add an optional child key for each regex/URL to determine which cookies should be handled ?

Cheers,

**Comment by lucmichalski** [comment]
Hi,

Thanks for the quick reply !

Globally, I would like to have the same kind of features for caching/not caching like varnish;.

For example, if you check this config file:
https://github.com/CleverCloud/varnish-examples/blob/master/prestashop.vcl

You can see that some regex are done for not passing to the server cache some urls or conditions based on the header or cookie values.

Ps. 
- Maybe it would be interesting to parse some varnish config files with https://github.com/KeisukeYamashita/go-vcl and create an interface for these regex rules.
- Do you have a telegram account ? my handle is deepocrates, could be easier to discuss more sensitive sides of my goal

Cheers,
Luc Michalski

**Comment by Darkweak** [comment]
Oh okay, but I've got some interrogations about that.
Do you want to be able to deny request from the cache system directly based on headers/cookies ?
Then you're idea gave me a way to manage headers (actually and cookies in a future release) from another way with regex.

I don't plan to implement a VCL support at the moment but if you want to include it in Souin I'll appreciate that.
I sent you a message on your telegram account/

Cheers,
