### ISSUE TITLE
Feature Request - Cache per devicetype/url

### ISSUE THREAD

**Issue by lucmichalski** [Darkweak/Souin#61]
Hi @Darkweak ,

Hope you are all well !

It would be awesome to create a filter on the user-agent to cache page per device types (desktop/tablet and mobile) like varnish plugin https://github.com/varnishcache/varnish-devicedetect.

It is just a collection of regexrules for setting up a prefix to cache key.

What do you think about that ? Does it inspire you an easy way to implement this layer ?

Ref. https://github.com/varnishcache/varnish-devicedetect/blob/master/devicedetect.vcl#L33-L110

Cheers,
Luc Michalski

**Comment by Darkweak** [comment]
Should be done in #82 .

**Comment by Darkweak** [comment]
You can use YKeys to group requests by regex headers now. In the future, the #66 will implement a deeper way to cache items.
