### ISSUE TITLE
Feature Request - Grafana/Prometheus dashboard

### ISSUE THREAD

**Issue by lucmichalski** [darkweak/souin#63]
Hi @Darkweak ,

Hope you are all well !

I wanted also tyo suggest the creation of grafana dashboard with a prometheus exporter. 

For my part, I am using a gin-gonic/prometheus middleware for feeding a grafana dahsboard. It also use a geoip2 middleware for a world map panel.

<img width="1434" alt="Screenshot 2021-04-09 at 06 36 52" src="https://user-images.githubusercontent.com/1963546/114824045-99896000-9dc4-11eb-952a-7609582d46aa.png">

Ref. 
- Gin+Prometheus+Geoip: https://github.com/penglongli/gin-metrics/issues/2

Cheers,
Luc Michalski

**Comment by polarathene** [comment]
Possible resources of interest if you pick up this feature:

- https://prometheus.io/docs/guides/go-application/
- https://github.com/prometheus/client_golang
- https://github.com/armon/go-metrics
- https://github.com/spacemonkeygo/monkit#metrics

**Comment by darkweak** [comment]
Added to the next release ✌️

**Comment by darkweak** [comment]
Available in the 1.5.11 final version.
