### ISSUE TITLE
404 response cached as 200

### ISSUE THREAD

**Issue by puckey** [Darkweak/Souin#83]
While testing this, I noticed that a 404 response comes back as 404 before being cached and then after being cached is being presented as 200. Shouldn't it present the 404 response status code instead?

A question following from this : is it possible to only cache results with 200 response status codes?

**Comment by Darkweak** [comment]
Hi @puckey thank you for your interest about Souin. It seems to be a regression, I'll make a hotfix about that and I'll add a test case to ensure this behaviour won't going back in the future.
An additional feature would be to select status codes to cache for each URL defined in the urls section.

I'll try my best to develop this asap. Stay tuned.
