### ISSUE TITLE
Usage with kubernetes and traefik

### ISSUE THREAD

**Issue by Allaux** [darkweak/souin#92]
Hello,
Do you have some example for usage with traefik on kubernetes ?

**Comment by Darkweak** [comment]
Hi @Allaux, it's on the roadmap to explicit the usage in the documentation and create an additional repository like it's done for prestashop and wordpress solutions.

**Comment by darkweak** [comment]
It's available as Træfik plugin so I'll drop the out-of-the-box support soon.
